<?php
/**
 * Created by PhpStorm.
 * User: simonezhou
 * Date: 2016/5/3
 * Time: 13:42
 */

namespace App\Controller;


use Cake\Core\Configure;
use Cake\ORM\TableRegistry;
use Phinx\Db\Table;

class BaseController extends AppController
{
    private $session;    //session信息
    public $userState;   //标志用户登陆状态
    private $loginTable; 

    //api验证身份
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this -> session = $this -> request -> session();
        $user_id = $this -> session -> read('user_id');
        $this -> userState = ($user_id == null || !isset($user_id)) ? Configure::read('LOGOUT_USER') : $user_id;
        $this -> loginTable = TableRegistry::get('Login');
    }

    //每次刷新页面，自动验证
    public function isAuthorized() {
        $this -> autoRender = false;
        $ret = array('code' => 1, 'info' => '登录成功');

        //判断是否已退出，没退出则获取user_name
        if ($this -> userState == Configure::read('LOGOUT_USER')) {
            $ret['code'] = 0;
            $ret['info'] = '已退出';
        } else {
            //获取数据库中的user_name
            $query = $this -> loginTable -> find() -> where(['user_id' => $this -> userState]);
            $result = $query -> toList();
            foreach ($result as $row) {
                $ret['user_name'] = $row['name'];
            }
        }
        $this -> response -> body(json_encode($ret));
    }

    //退出登陆状态
    public function logout() {
        $this -> autoRender = false;
        $ret = array('code' => 0, 'info' => '已退出');

        $this -> session -> destroy();
        $this -> userState = Configure::read('LOGOUT_USER');
        $this -> response -> body(json_encode($ret));
    }
}