<?php
/**
 * Created by PhpStorm.
 * User: simonezhou
 * Date: 2016/5/15
 * Time: 21:18
 */

namespace App\Controller;

use Cake\Core\Configure;
use Cake\ORM\TableRegistry;
use Cake\I18n\Date;

class IndexController extends BaseController
{
    public $accountTable;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this -> accountTable = TableRegistry::get('Account');
    }

    //初始化Index页面(api)
    public function getIndexData() {
        $this -> autoRender = false;
        $ret = array('code' => 1, 'info' => '', 'data' => array());

        if ($this -> userState == Configure::read('LOGOUT_USER')) {
            $ret['code'] = 0;
            $ret['info'] = '已退出';
        } else if ($this -> request -> is('ajax')) {
            $now = Date::now();

            $today = $now -> format('Y-m-d');
            $yesterday = $now -> subDay(1) -> format('Y-m-d');

            $ret['data']['todayExpense'] = $this -> _getDateSum(Configure::read('EXPENSE_ACCOUNT'), $today);
            $ret['data']['todayIncome'] = $this -> _getDateSum(Configure::read('INCOME_ACCOUNT'), $today);
            $ret['data']['yesterdayExpense'] = $this -> _getDateSum(Configure::read('EXPENSE_ACCOUNT'), $yesterday);
            $ret['data']['yesterdayIncome'] = $this -> _getDateSum(Configure::read('INCOME_ACCOUNT'), $yesterday);

            $ret['data']['tenDaysTime'] = array();
            $ret['data']['tenDaysExpense'] = array();
            $ret['data']['tenDaysIncome'] = array();
            for ($i = 9; $i >= 0; --$i) {
                $now = Date::now();
                $date = $now -> subDays($i) -> format('Y-m-d');
                array_push($ret['data']['tenDaysTime'], $date);
                array_push($ret['data']['tenDaysExpense'], $this -> _getDateSum(Configure::read('EXPENSE_ACCOUNT'), $date));
                array_push($ret['data']['tenDaysIncome'], $this -> _getDateSum(Configure::read('INCOME_ACCOUNT'), $date));
            }
        }

        $this -> response ->body(json_encode($ret));
    }

    private function _getDateSum($classifyId, $date) {
        $query = $this -> accountTable -> find() -> select('sum')
                       -> where([   'user_id' => $this -> userState,
                                    'classify_id' => $classifyId,
                                    'date =' => $date ]);
        $ret = $query -> sumOf('sum');

        return $ret;
    }
}