<?php
/**
 * Created by PhpStorm.
 * User: simone
 * Date: 2016/4/18
 * Time: 17:49
 */

namespace App\Controller;

use Cake\ORM\TableRegistry;

class LoginController extends AppController {
    private $loginTable;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this -> loginTable = TableRegistry::get('Login');
    }

    public function login() {
        $this -> autoRender = false;
        $ret = array('code' => 1, 'info' => '登录成功');

        if ($this -> request -> is('ajax')) {
            $loginName = $this -> request -> data['name'];
            $loginPassword = $this -> request -> data['password'];

            $query = $this -> loginTable -> find() -> where(['name' => $loginName, 'password' => $loginPassword]);
            $result = $query -> toList();

            if ($result == array()) {
                $ret['code'] = 0;
                $ret['info'] = '用户名或密码错误';
            } else {
                $session = $this -> request -> session();
                $session -> write([
                    'user_id' => $result[0]['user_id'],
                    'user_name' => $result[0]['name']
                ]);
            }

            $this -> response -> body (json_encode($ret));
        }
    }

    public function register() {
        $this -> autoRender = false;
        $ret = array('code' => 1, 'info' => '注册成功');

        if ($this -> request -> is('ajax')) {
            $registerName = $this -> request -> data['name'];
            $registerPassword = $this -> request -> data['password'];
            $registerEmail = $this -> request -> data['email'];
            $registerPersonal = isset($this -> request -> data['personal']) ? $this -> request -> data['personal'] : null;

            //检查用户名是否存在
            $query = $this -> loginTable -> find() -> where(['name' => $registerName]);
            $result = $query -> toList();
            if ($result != array()) {
                $ret['code'] = 0;
                $ret['info'] = '该用户名已存在';
            } else {
                $newUser = $this -> loginTable -> newEntity();
                $newUser -> name = $registerName;
                $newUser -> password = $registerPassword;
                $newUser -> email = $registerEmail;
                $newUser -> personal = $registerPersonal;
                $this -> loginTable -> save($newUser);
            }

            $this -> response -> body (json_encode($ret));
        }
    }
}