<?php
/**
 * Created by PhpStorm.
 * User: simonezhou
 * Date: 2016/5/4
 * Time: 17:13
 */

namespace App\Model\Table;

use Cake\ORM\Table;

class AccountTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this -> belongsTo('Item', [
            'className' => 'Parameter',
            'foreignKey' => 'item_id',
            'propertyName' => 'item'
        ]);
        $this -> belongsTo('Method', [
            'className' => 'Parameter',
            'foreignKey' => 'method_id',
            'propertyName' => 'method'
        ]);
        $this -> belongsTo('Member', [
            'className' => 'Parameter',
            'foreignKey' => 'member_id',
            'propertyName' => 'member'
        ]);
        $this -> belongsTo('Seller', [
            'className' => 'Parameter',
            'foreignKey' => 'seller_id',
            'propertyName' => 'seller'
        ]);
    }

}