<?php
/**
 * Created by PhpStorm.
 * User: simonezhou
 * Date: 2016/5/4
 * Time: 17:37
 */

namespace App\Model\Table;

use Cake\ORM\Table;

class ParameterTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this -> hasOne('Account', [
            'foreignKey' => 'item_id'
        ]);
    }
}